### ISSUE TITLE
Issues Connecting to PSQL

### ISSUE THREAD

**Issue by diegoh01** [evdubs/oic-options-chains#2]
I first downloaded the .Zip and opened the extract.rkt file and got all the required packages running beforehand. I then set up a new DB in my PSQL in localhost. It says the user is "postgres", I named the db "Chains" and had a simple password. This is how my code looked (this is the only section I actually wrote in, since I'm assuming it's the only input it required from my part):

`(define dbc (postgresql-connect #:user ("postgres") #:database ("Chains") #:password ("XXXX")))`

this returns the following error:

application: not a procedure;
 expected a procedure that can be applied to arguments
  given: "postgres"
  arguments...: [none]

Is my username wrong? Did I have to set something else up before this? I'm sorry for the very nooby questions, I work mainly on modeling through R and Python. Any possible pointers on how to fix this are greatly appreciated!

**Comment by evdubs** [comment]
You shouldn't need to edit the code to supply the user/db/password arguments. You can just do:

```bash
$ racket extract.rkt -u postgres -d Chains -p XXXX
```

This is documented when you use the `-h` flag:

```bash
$ racket extract.rkt -h
racket extract.rkt [ <option> ... ]
 where <option> is one of
  -f <first>, --first-symbol <first> : First symbol to query. Defaults to nothing
  -l <last>, --last-symbol <last> : Last symbol to query. Defaults to nothing
  -n <name>, --db-name <name> : Database name. Defaults to 'local'
  -p <password>, --db-pass <password> : Database password
  -u <user>, --db-user <user> : Database user name. Defaults to 'user'
  --help, -h : Show this help
  -- : Do not treat any remaining argument as a switch (at this level)
 Multiple single-letter switches can be combined after one `-'; for
  example: `-h-' is the same as `-h --'
```

The error you get is because, in Lisp, putting something in parens means evaluate it. It's like if you did `"postgres"()` in Python. So, with your code, you really wanted:

```racket
(define dbc (postgresql-connect #:user "postgres" #:database "Chains" #:password "XXXX"))
```

The code that you changed makes use of parameters; these are enclosed in parens to get their value.

**Comment by evdubs** [comment]
Have you made progress on this issue?

**Comment by evdubs** [comment]
User has moved on to other things.
